### ISSUE TITLE
Error with Markdown 3.3

### ISSUE THREAD

**Issue by yoongkang** [Zopieux/py-gfm#24]
`FencedBlockProcessor` now expects a `config` dict passed into it, among other things.

```
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Users/yoongkang/business/backend-dev/lib/python3.8/site-packages/markdown/extensions/__init__.py", line 77, in _extendMarkdown
    self.extendMarkdown(md)
  File "/Users/yoongkang/business/backend-dev/lib/python3.8/site-packages/mdx_gfm/__init__.py", line 55, in extendMarkdown
    PartialGithubFlavoredMarkdownExtension.extendMarkdown(self, md)
  File "/Users/yoongkang/business/backend-dev/lib/python3.8/site-packages/mdx_partial_gfm/__init__.py", line 65, in extendMarkdown
    gfm.StandaloneFencedCodeExtension().extendMarkdown(md)
  File "/Users/yoongkang/business/backend-dev/lib/python3.8/site-packages/gfm/standalone_fenced_code.py", line 37, in extendMarkdown
    processor = FencedBlockPreprocessor(md)
TypeError: __init__() missing 1 required positional argument: 'config'
```

To anyone getting the same problem, just downgrade `python-markdown` to 3.2.

**Comment by Zopieux** [comment]
Please try with the new 1.0.1 release (#25) and open if you still have an issue.
