### ISSUE TITLE
Issue with Markdown 3.3.2

### ISSUE THREAD

**Issue by sirishkumargists** [Zopieux/py-gfm#26]
# Installed packages

pip list
importlib-metadata 2.0.0  
Markdown           3.3.2  
pip                18.1   
py-gfm             1.0.0  
setuptools         40.6.2 
zipp               3.3.1  

# Code with issues

> import markdown
   from mdx_gfm import GithubFlavoredMarkdownExtension
   html = markdown.markdown("", extensions=[GithubFlavoredMarkdownExtension()])

# Expected
No error

# Error 

html = markdown.markdown("Hello World!", extensions=[GithubFlavoredMarkdownExtension()])
Traceback (most recent call last):
  File "/work/tmp/cp/venv/lib/python3.6/site-packages/markdown/extensions/__init__.py", line 77, in _extendMarkdown
    self.extendMarkdown(md)
  File "/work/tmp/cp/venv/lib/python3.6/site-packages/mdx_gfm/__init__.py", line 55, in extendMarkdown
    PartialGithubFlavoredMarkdownExtension.extendMarkdown(self, md)
  File "/work/tmp/cp/venv/lib/python3.6/site-packages/mdx_partial_gfm/__init__.py", line 65, in extendMarkdown
    gfm.StandaloneFencedCodeExtension().extendMarkdown(md)
  File "/work/tmp/cp/venv/lib/python3.6/site-packages/gfm/standalone_fenced_code.py", line 37, in extendMarkdown
    processor = FencedBlockPreprocessor(md)
TypeError: __init__() missing 1 required positional argument: 'config'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/work/tmp/cp/venv/lib/python3.6/site-packages/markdown/core.py", line 385, in markdown
    md = Markdown(**kwargs)
  File "/work/tmp/cp/venv/lib/python3.6/site-packages/markdown/core.py", line 96, in __init__
    configs=kwargs.get('extension_configs', {}))
  File "/work/tmp/cp/venv/lib/python3.6/site-packages/markdown/core.py", line 124, in registerExtensions
    ext._extendMarkdown(self)
  File "/work/tmp/cp/venv/lib/python3.6/site-packages/markdown/extensions/__init__.py", line 81, in _extendMarkdown
    self.extendMarkdown(md, {})

This issue may be related to https://github.com/Zopieux/py-gfm/issues/24

**Comment by Zopieux** [comment]
Please try with the new 1.0.1 release (#25) and open if you still have an issue.
